"""A module for Natural Language Understanding provided by rasa_nlu"""

from retico.core import abstract
from retico.core.text.common import SpeechRecognitionIU
from retico.core.dialogue.common import DialogueActIU

from rasa_nlu.config import RasaNLUConfig
from rasa_nlu.model import Interpreter


class RasaNLUModule(abstract.AbstractModule):
    """A standard rasa NLU module.

    Attributes:
        model_dir (str): The path to the directory of the NLU model generated by
            rasa_nlu.train.
        config_file (str): The path to the json file containing the rasa nlu
            configuration.
    """

    @staticmethod
    def name():
        return "Rasa NLU Module"

    @staticmethod
    def description():
        return "A Module providing Natural Language Understanding by rasa_nlu"

    @staticmethod
    def input_ius():
        return [SpeechRecognitionIU]

    @staticmethod
    def output_iu():
        return DialogueActIU

    def __init__(self, model_dir, config_file, **kwargs):
        super().__init__(**kwargs)
        self.model_dir = model_dir
        self.config_file = config_file
        self.interpreter = None
        self.cache = None

    def process_iu(self, input_iu):
        if input_iu.get_text() == self.cache:
            return None
        self.cache = input_iu.get_text()
        result = self.interpreter.parse(input_iu.get_text())
        concepts = {}
        for entity in result.get("entities"):
            concepts[entity["entity"]] = entity["value"]
        act = result["intent"]["name"]
        confidence = result["intent"]["confidence"]
        output_iu = self.create_iu(input_iu)
        output_iu.set_act(act, concepts, confidence)
        return output_iu

    def setup(self):
        nluconf = RasaNLUConfig(self.config_file)
        self.interpreter = Interpreter.load(self.model_dir, nluconf)
